In [1]:
import pandas as pd

In [2]:
data = {'Name': ['Alice', 'Bob'], 'Age': [25, 30]}
df = pd.DataFrame(data)

In [3]:
lst = [['Alice', 25], ['Bob', 30]]
df = pd.DataFrame(lst, columns=['Name', 'Age'])

In [4]:
df.head()

    Name  Age
0  Alice   25
1    Bob   30

In [5]:
df.tail()

    Name  Age
0  Alice   25
1    Bob   30

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    2 non-null      str
 1   Age     2 non-null      int64
dtypes: int64(1), str(1)
memory usage: 164.0 bytes

In [7]:
df.describe()

             Age
count   2.000000
mean   27.500000
std     3.535534
min    25.000000
25%    26.250000
50%    27.500000
75%    28.750000
max    30.000000

In [8]:
df['Name']

0    Alice
1      Bob
Name: Name, dtype: str

In [9]:
df[['Name', 'Age']]

    Name  Age
0  Alice   25
1    Bob   30

In [10]:
df.loc[0]

Name    Alice
Age        25
Name: 0, dtype: object

In [11]:
df.iloc[1]

Name    Bob
Age      30
Name: 1, dtype: object

In [12]:
df[df['Age'] > 25]

  Name  Age
1  Bob   30

In [13]:
df['Gender'] = ['F', 'M']
print(df)

    Name  Age Gender
0  Alice   25      F
1    Bob   30      M

In [14]:
df.drop('Age', axis=1, inplace=True)
print(df)
df['Age'] = [25, 30]

    Name Gender
0  Alice      F
1    Bob      M

In [15]:
df.isnull()

    Name  Gender    Age
0  False   False  False
1  False   False  False

In [16]:
df.dropna()

    Name Gender  Age
0  Alice      F   25
1    Bob      M   30

In [17]:
df.fillna(0)

    Name Gender  Age
0  Alice      F   25
1    Bob      M   30

In [18]:
df.groupby('Gender')['Age'].mean()
print(df)

    Name Gender  Age
0  Alice      F   25
1    Bob      M   30

In [19]:
dt={'Marks':[90,95]}
df1=pd.DataFrame(dt)

In [20]:
df2=pd.DataFrame({'Name':['Alice','David'],'Gender':['F','M'],'Age':[30,40]})
pd.merge(df, df2, on = 'Name')

    Name Gender_x  Age_x Gender_y  Age_y
0  Alice        F     25        F     30

In [21]:
print(df1)

   Marks
0     90
1     95

In [22]:
print(df.join(df1))

    Name Gender  Age  Marks
0  Alice      F   25     90
1    Bob      M   30     95

In [23]:
df = pd.read_csv('data.csv')

EmptyDataError: No columns to parse from file

In [ ]:
df.to_csv('output.csv', index=False)

In [ ]:
df.sort_values('Age')

In [ ]:
df['Age'].apply(lambda x: x + 1)

In [ ]:
df['Name'].unique()

In [ ]:
df['Age'].value_counts()